compiler:
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
language: cpp
script:
  - chmod a+x ./test.sh
  - make Debug CXX="${CXX}" && ./test.sh
